# Generated by Django 5.2 on 2025-04-05 10:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
