# Generated by Django 5.2 on 2025-04-06 09:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=users.models.upload_to, verbose_name='image'),
        ),
    ]
