# Generated by Django 5.2 on 2025-04-06 14:10

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=users.models.upload_to, verbose_name='image'),
        ),
    ]
